obj-$(CONFIG_HISILICON_PLATFORM_MAILBOX)	+= mailbox/
obj-$(CONFIG_HIFI_DSP_ONE_TRACK)                += hifi_dsp/
obj-$(CONFIG_HIFI_MAILBOX)                      += hifi_mailbox/
obj-$(CONFIG_HISI_ICS_IPU)                  += ics/
