/*
 * Copyright (c) 2016-2017 Linaro Ltd.
 * Copyright (c) 2016-2017 HiSilicon Technologies Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */
#ifndef HISI_ISP_ISR_DEF_H
#define HISI_ISP_ISR_DEF_H

#include "hisi_isp_core.h"

#define SKIP_FRAME_NUM              (4)
#define ISP_BASE_ADDR_IRQ_MERGER              (0x00025000)
#define ISP_BASE_ADDR_IRQ_MERGER2             (0x0002C000)

enum IRQ_MERGER_TYPE {
	IRQ_MERGER_DEBUG_0  = 0x0,
	IRQ_MERGER_DEBUG_1  = 0x20,
	IRQ_MERGER_DEBUG_2  = 0x40,
	IRQ_MERGER_DEBUG_3  = 0x60,
	IRQ_MERGER_DEBUG_4  = 0x80,
	IRQ_MERGER_ERROR_0  = 0xE0,
	IRQ_MERGER_ERROR_1  = 0x100,
	IRQ_MERGER_FRPROC_0 = 0x120,
	IRQ_MERGER_FRPROC_1 = 0x140,
	IRQ_MERGER_FRPROC_2 = 0x160,
	IRQ_MERGER_COMBINED = 0x1A0,
	IRQ_MERGER_IRQ_MAX  = 0xFF,
};

enum IRQ_MERGER_FUNC_TYPE {
	IRQ_MERGER_FUNC_IMS  = 0x0,
	IRQ_MERGER_FUNC_RIS  = 0x4,
	IRQ_MERGER_FUNC_MIS  = 0x8,
	IRQ_MERGER_FUNC_ICR  = 0xC,
	IRQ_MERGER_FUNC_ISR  = 0x10,
	IRQ_MERGER_FUNC_NO   = 0x1F,
};

#define IRQ_MERGER_IMSC_DEBUG0 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_0)
#define IRQ_MERGER_IMSC_DEBUG1 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_1)
#define IRQ_MERGER_IMSC_DEBUG2 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_2)
#define IRQ_MERGER_IMSC_DEBUG3 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_3)
#define IRQ_MERGER_IMSC_ERROR0 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_ERROR_0)
#define IRQ_MERGER_IMSC_ERROR1 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_ERROR_1)
#define IRQ_MERGER_IMSC_FRPROC0 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_FRPROC_0)
#define IRQ_MERGER_IMSC_FRPROC1 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_FRPROC_1)
#define IRQ_MERGER_IMSC_FRPROC2 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_FRPROC_2)

#define IRQ_MERGER_ICR_DEBUG0 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_0 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_DEBUG1 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_1 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_DEBUG2 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_2 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_DEBUG3 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_DEBUG_3 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_ERROR0 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_ERROR_0 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_ERROR1 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_ERROR_1 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_FRPROC0 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_FRPROC_0 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_FRPROC1 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_FRPROC_1 + IRQ_MERGER_FUNC_ICR)
#define IRQ_MERGER_ICR_FRPROC2 \
	(ISP_BASE_ADDR_IRQ_MERGER2 + IRQ_MERGER_FRPROC_2 + IRQ_MERGER_FUNC_ICR)

#define IRQ_MERGER_SR_4_CVDR_RT_SOF_VPWR_23_OFFSET     17
#define IRQ_MERGER_SR_4_CVDR_RT_EOF_VPWR_23_OFFSET     21

void isp_enable_irq(struct isp_device *dev);
void isp_clear_irq_state(struct isp_device *dev);

irqreturn_t isp_vic1_handler(int irq, void *dev_id);
irqreturn_t isp_frproc0_handler(int irq, void *dev_id);

#endif /* HISI_ISP_ISR_DEF_H */
